# Generated by Django 5.2 on 2025-04-10 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JaapCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JaapSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ram_count', models.PositiveIntegerField(default=0)),
                ('timer_set', models.PositiveIntegerField(blank=True, choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '60 Minutes')], null=True)),
                ('target_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jaap_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
